name: Deploy Docs

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '_config.yml'
      - '.github/workflows/deploy-docs.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          npm install -g gh-pages

      - name: Deploy
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          gh-pages -d docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
